/**
 * @file   generator.ts
 * @notice TableAst → Solidity contract + TypeScript SDK bindings + ABI
 *
 * The generator is purely deterministic: same AST in, same output out.
 * No filesystem access, no randomness.
 */

import {
  Abi,
  AbiFunctionDef,
  AbiParam,
  CompilerOutput,
  FieldDef,
  SQL_TO_SOLIDITY,
  SQL_TO_TS,
  TableAst,
} from './types.js';
import { ethers } from 'ethers';

// ─────────────────────────────────────────────────────────────
//  Name helpers
// ─────────────────────────────────────────────────────────────

function toPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

// ─────────────────────────────────────────────────────────────
//  ABI builder helpers
// ─────────────────────────────────────────────────────────────

function fn(
  name: string,
  inputs: AbiParam[],
  outputs: AbiParam[],
  mutability: 'pure' | 'view' | 'nonpayable' | 'payable' = 'nonpayable'
): AbiFunctionDef {
  return { type: 'function', name, inputs, outputs, stateMutability: mutability };
}

function p(name: string, type: string, internalType?: string): AbiParam {
  return { name, type, internalType: internalType ?? type };
}

// ─────────────────────────────────────────────────────────────
//  Schema → on-chain schemaBytes (ABI-encoded for storage)
// ─────────────────────────────────────────────────────────────

function encodeSchemaBytes(ast: TableAst): string {
  const abiCoder = ethers.AbiCoder.defaultAbiCoder();
  const fieldNames   = ast.fields.map((f) => f.name);
  const fieldTypes   = ast.fields.map((f) => f.type);
  const fieldPrimary = ast.fields.map((f) => f.primary);
  const fieldCounter = ast.fields.map((f) => f.counter ?? false);
  const encoded = abiCoder.encode(
    ['string', 'string[]', 'string[]', 'bool[]', 'bool[]'],
    [ast.table, fieldNames, fieldTypes, fieldPrimary, fieldCounter]
  );
  return encoded;
}

// ─────────────────────────────────────────────────────────────
//  Solidity generator
// ─────────────────────────────────────────────────────────────

function generateSolidity(ast: TableAst, contractName: string): string {
  const fieldDocs = ast.fields
    .map((f) => `${f.name}:${f.type}${f.primary ? ' (PK)' : ''}`)
    .join(', ');

  const pkField   = ast.fields.find((f) => f.primary)!;
  const pkSolType = SQL_TO_SOLIDITY[pkField.type]; // always uint256

  return `\
// SPDX-License-Identifier: MIT
// Generated by @web3ql/compiler — DO NOT EDIT
// Table: ${ast.table}  Fields: ${fieldDocs}
pragma solidity ^0.8.20;

import "../contracts/Web3QLTable.sol";

/**
 * @title  ${contractName}
 * @notice Web3QL encrypted table for "${ast.table}".
 *         Schema: ${fieldDocs}
 *
 * Key derivation:
 *   bytes32 key = keccak256(abi.encodePacked("${ast.table}", id))
 *
 * All read/write operations delegate to Web3QLTable's encrypted storage.
 */
contract ${contractName} is Web3QLTable {

    // ----------------------------------------------------------
    //  Key derivation — deterministic, collision-resistant
    // ----------------------------------------------------------

    function _getKey(${pkSolType} id) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked("${ast.table}", id));
    }

    // ----------------------------------------------------------
    //  CRUD helpers (thin wrappers adding uint id → bytes32 key)
    // ----------------------------------------------------------

    function insert(
        ${pkSolType}  id,
        bytes calldata ciphertext,
        bytes calldata encryptedKey
    ) external {
        write(_getKey(id), ciphertext, encryptedKey);
    }

    function readRecord(
        ${pkSolType} id
    ) external view returns (
        bytes memory ciphertext,
        bool         deleted,
        uint256      version,
        uint256      updatedAt,
        address      owner_
    ) {
        return read(_getKey(id));
    }

    function updateRecord(
        ${pkSolType}  id,
        bytes calldata ciphertext,
        bytes calldata encryptedKey
    ) external {
        update(_getKey(id), ciphertext, encryptedKey);
    }

    function deleteRecordById(${pkSolType} id) external {
        deleteRecord(_getKey(id));
    }

    // ----------------------------------------------------------
    //  Access control helpers
    // ----------------------------------------------------------

    function grantRecordAccess(
        ${pkSolType}  id,
        address        user,
        Role           role,
        bytes calldata encryptedKeyForUser
    ) external {
        grantAccess(_getKey(id), user, role, encryptedKeyForUser);
    }

    function revokeRecordAccess(${pkSolType} id, address user) external {
        revokeAccess(_getKey(id), user);
    }

    function getEncryptedKey(${pkSolType} id) external view returns (bytes memory) {
        return getMyEncryptedKey(_getKey(id));
    }

    // ----------------------------------------------------------
    //  Views
    // ----------------------------------------------------------

    function recordExists(${pkSolType} id) external view returns (bool) {
        return recordExists(_getKey(id));
    }

    function recordOwner(${pkSolType} id) external view returns (address) {
        return _records[_getKey(id)].owner;
    }

    function getCollaboratorCount(${pkSolType} id) external view returns (uint8) {
        return collaboratorCount(_getKey(id));
    }
}
`;
}

// ─────────────────────────────────────────────────────────────
//  ABI builder
// ─────────────────────────────────────────────────────────────

const RECORD_TUPLE_OUTPUT: AbiParam = {
  name: '',
  type: 'tuple',
  internalType: 'struct Web3QLTable.RecordMeta',
  components: [
    p('ciphertext', 'bytes'),
    p('deleted',    'bool'),
    p('version',    'uint256'),
    p('updatedAt',  'uint256'),
    p('owner_',     'address'),
  ],
};

function buildAbi(): Abi {
  return [
    // CRUD
    fn('insert',           [p('id','uint256'), p('ciphertext','bytes'), p('encryptedKey','bytes')],     []),
    fn('readRecord',       [p('id','uint256')],
      [p('ciphertext','bytes'), p('deleted','bool'), p('version','uint256'), p('updatedAt','uint256'), p('owner_','address')],
      'view'
    ),
    fn('updateRecord',     [p('id','uint256'), p('ciphertext','bytes'), p('encryptedKey','bytes')],     []),
    fn('deleteRecordById', [p('id','uint256')],                                                         []),
    // Access control
    fn('grantRecordAccess',  [p('id','uint256'), p('user','address'), p('role','uint8'), p('encryptedKeyForUser','bytes')], []),
    fn('revokeRecordAccess', [p('id','uint256'), p('user','address')],                                  []),
    fn('getEncryptedKey',    [p('id','uint256')],  [p('','bytes')], 'view'),
    // Views
    fn('recordExists',       [p('id','uint256')],   [p('','bool')],    'view'),
    fn('recordOwner',        [p('id','uint256')],   [p('','address')], 'view'),
    fn('getCollaboratorCount', [p('id','uint256')], [p('','uint8')],   'view'),
    // Counter / Relation
    fn('counterValue',   [p('targetKey','bytes32'), p('field','bytes32')], [p('','uint256')], 'view'),
    fn('registerWire',   [p('wire','address'), p('fields','bytes32[]')],   []),
    fn('revokeWire',     [p('wire','address'), p('fields','bytes32[]')],   []),
    fn('increment',      [p('targetKey','bytes32'), p('field','bytes32'), p('amount','uint256')], []),
    // Events from Web3QLTable
    {
      type: 'event', name: 'RecordWritten',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('owner','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'RecordUpdated',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('actor','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'RecordDeleted',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('owner','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'AccessGranted',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('user','address'), indexed: true } as any,
        p('role','uint8'),
      ],
    },
    {
      type: 'event', name: 'AccessRevoked',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('user','address'), indexed: true } as any,
      ],
    },
  ];
}

// ─────────────────────────────────────────────────────────────
//  TypeScript SDK bindings generator
// ─────────────────────────────────────────────────────────────

function generateSdkBindings(ast: TableAst, contractName: string): string {
  const pk     = ast.fields.find((f) => f.primary)!;
  const pkTs   = SQL_TO_TS[pk.type]; // bigint

  // COUNTER fields live on-chain — exclude from the encrypted record type
  const encryptedFields = ast.fields.filter((f: FieldDef) => !f.counter);
  const counterFields   = ast.fields.filter((f: FieldDef) => f.counter);

  // Template variables used inside the return string
  const encryptedFieldNames     = encryptedFields.filter((f: FieldDef) => !f.primary).map((f: FieldDef) => `${f.name}: ...`).join(', ');
  const counterFieldNamesLiteral = counterFields.map((f: FieldDef) => `'${f.name}'`).join(', ');

  const fieldTypes = encryptedFields
    .map((f: FieldDef) => `  ${f.name}: ${SQL_TO_TS[f.type]};`)
    .join('\n');

  const counterInterface = counterFields.length > 0
    ? `\n/** On-chain counter fields — readable via counterValue(), NOT stored in ciphertext */\nexport interface ${toPascal(ast.table)}Counters {\n` +
      counterFields.map((f: FieldDef) => `  ${f.name}: bigint;`).join('\n') +
      '\n}\n'
    : '';

  // Per-counter read methods
  const counterMethods = counterFields.map((f: FieldDef) => `
  /**
   * Read on-chain counter \`${f.name}\` for a given record id.
   * Public — no decryption required.
   */
  async ${f.name}(id: ${pkTs}): Promise<bigint> {
    const field = ethers.keccak256(ethers.toUtf8Bytes('${f.name}'));
    const raw = await (this as any)._contract['counterValue'](this.key(id), field);
    return BigInt(raw);
  }`).join('');

  // Per-wire relatedWrite methods
  const wireMethods = (ast.wires ?? []).map((wire) => {
    const isPayable = wire.updates.some((u) => u.value === 'payment');
    const allowedTokens = wire.rules.allowedTokens ?? ['0x0000000000000000000000000000000000000000'];
    const allowedTokensLiteral = allowedTokens.map((t) => `'${t}'`).join(', ');
    return `
  /**
   * Write to this table via the '${wire.targetTable}' RelationWire.
   * Atomically updates counters on '${wire.targetTable}' in the same tx.
   *
   * Allowed tokens : [${allowedTokensLiteral}]
   * (address(0) = native CELO; others = ERC-20 — pre-approve wire first)
   *
   * @param wireAddress  Deployed Web3QLRelationWire address
   * @param id           Primary key of the NEW source record
   * @param payload      Serialised row
   * @param targetId     Primary key of the TARGET record in '${wire.targetTable}'${isPayable ? "\n   * @param token        Payment token (ethers.ZeroAddress = native CELO)\n   * @param amount       Payment amount (wei for native, token units for ERC-20)" : ''}
   */
  async relatedWrite(
    wireAddress : string,
    id          : ${pkTs},
    payload     : string,
    targetId    : ${pkTs},${isPayable ? "\n    token       : string = ethers.ZeroAddress,\n    amount      : bigint = 0n," : ''}
  ): Promise<ethers.TransactionReceipt> {
    const { ciphertext, encryptedKey } = await (this as any).encryptForSelf(payload);
    const sourceKey = this.key(id);
    const targetKey = this.deriveKey('${wire.targetTable}', targetId);
    const wireContract = new ethers.Contract(wireAddress, RELATION_WIRE_ABI, (this as any).signer);
    const isNative  = !token || token === ethers.ZeroAddress;
    const txOpts    = isNative ? { value: amount } : {};
    const erc20Amt  = isNative ? 0n : amount;
    const tx = await wireContract['relatedWrite'](
      sourceKey, ciphertext, encryptedKey, targetKey,
      ${isPayable ? 'isNative ? ethers.ZeroAddress : token, erc20Amt, txOpts' : 'ethers.ZeroAddress, 0n'}
    );
    return tx.wait();
  }`;
  }).join('');

  const relayWireAbi = (ast.wires ?? []).length > 0 ? `
const RELATION_WIRE_ABI = [
  'function relatedWrite(bytes32 sourceKey, bytes ciphertext, bytes encryptedKey, bytes32 targetKey, address token, uint256 amount) payable',
  'function withdrawProjectFunds(bytes32 targetKey, address token, address to) external',
  'function withdrawAllProjectFunds(bytes32 targetKey, address to) external',
  'function projectBalances(bytes32 targetKey) external view returns (address[] tokens, uint256[] balances)',
  'function getAllowedTokens() external view returns (address[])',
] as const;
` : '';

  return `\
/**
 * Auto-generated Web3QL SDK bindings for "${ast.table}".
 * DO NOT EDIT — regenerate via: web3ql compile
 *
 * Depends on @web3ql/sdk for end-to-end encrypted read/write.
 */
import { ethers }                                            from 'ethers';
import {
  EncryptedTableClient,
  PublicKeyRegistryClient,
  Role,
  Model,
  type EncryptionKeypair,
  type RawRecord,
  type SchemaDefinition,
}                                                            from '@web3ql/sdk';

// ── Encrypted record fields (stored in ciphertext) ──────────
export interface ${toPascal(ast.table)}Record {
${fieldTypes}
}
${counterInterface}${relayWireAbi}
const TABLE_NAME = '${ast.table}';

// ── Typed client ─────────────────────────────────────────────
/**
 * ${contractName}Client — encrypted read/write for the "${ast.table}" table.
 *
 * @example
 *   const client = new ${contractName}Client(tableAddress, signer, keypair);
 *
 *   // Write (auto-encrypts)
 *   await client.insert(1n, JSON.stringify({ id: 1, name: 'Alice' }));
 *
 *   // Read (auto-decrypts)
 *   const data = await client.read(1n);
 *   const row  = JSON.parse(data) as ${toPascal(ast.table)}Record;
 *
 *   // Share with Bob (Bob must be registered in the PublicKeyRegistry)
 *   await client.share(1n, bobAddress, Role.VIEWER, registry);
 */
export class ${contractName}Client extends EncryptedTableClient {

  constructor(
    tableAddress : string,
    signer       : ethers.Signer,
    keypair      : EncryptionKeypair,
  ) {
    super(tableAddress, signer, keypair);
  }

  // ── Key derivation ──────────────────────────────────────────

  /** Derive the on-chain bytes32 key for a record id. */
  key(id: ${pkTs}): string {
    return this.deriveKey(TABLE_NAME, id);
  }

  // ── CRUD ────────────────────────────────────────────────────

  /**
   * Insert a new encrypted record.
   * @param id      Primary key value.
   * @param payload Serialised row — e.g. JSON.stringify(row).
   */
  async insert(id: ${pkTs}, payload: string): Promise<ethers.TransactionReceipt> {
    return this.writeRaw(this.key(id), payload);
  }

  /**
   * Read and decrypt a record.
   * Returns the raw string you passed to insert() / update().
   */
  async read(id: ${pkTs}): Promise<string> {
    return this.readPlaintext(this.key(id));
  }

  /**
   * Read as raw bytes (if you stored binary data).
   */
  async readBytes(id: ${pkTs}): Promise<Uint8Array> {
    return super.readBytes(this.key(id));
  }

  /**
   * Get the raw on-chain record (still encrypted).
   */
  async readRaw(id: ${pkTs}): Promise<RawRecord> {
    return super.readRaw(this.key(id));
  }

  /**
   * Update an existing record.
   * Rotates the symmetric key — call reshare() afterwards if needed.
   */
  async update(id: ${pkTs}, payload: string): Promise<ethers.TransactionReceipt> {
    return this.updateRaw(this.key(id), payload);
  }

  /** Delete a record and scrub all collaborator key copies. */
  async del(id: ${pkTs}): Promise<ethers.TransactionReceipt> {
    return this.deleteRecord(this.key(id));
  }

  // ── Sharing ─────────────────────────────────────────────────

  /**
   * Share a record with another address.
   * They must have registered their public key in the PublicKeyRegistry.
   */
  async share(
    id        : ${pkTs},
    recipient : string,
    role      : Role,
    registry  : PublicKeyRegistryClient,
  ): Promise<ethers.TransactionReceipt> {
    return super.share(this.key(id), recipient, role, registry);
  }

  /** Revoke a user's access to a record. */
  async revoke(id: ${pkTs}, user: string): Promise<ethers.TransactionReceipt> {
    return super.revoke(this.key(id), user);
  }

  // ── Views ────────────────────────────────────────────────────

  async exists(id: ${pkTs}): Promise<boolean> {
    return super.exists(this.key(id));
  }

  async owner(id: ${pkTs}): Promise<string> {
    return super.owner(this.key(id));
  }

  async collaboratorCount(id: ${pkTs}): Promise<number> {
    return super.collaboratorCount(this.key(id));
  }
${counterMethods}${wireMethods}
}

// ── ORM Model ────────────────────────────────────────────────
/**
 * ${contractName}Model — Web3QL ORM entry point for "${ast.table}".
 *
 * Wraps TypedTableClient + on-chain counters + relation writes.
 * Counter fields are merged automatically into every find() result.
 *
 * @example
 *   const ${ast.table} = new ${contractName}Model(tableAddress, signer, keypair);
 *
 *   // Create
 *   await ${ast.table}.create(1n, { ${encryptedFieldNames} });
 *
 *   // Find — counters merged in automatically
 *   const row = await ${ast.table}.findUnique(1n);
 *
 *   // Relation write (native CELO)
 *   await ${ast.table}.relatedCreate({ wire, id: 2n, data, targetId: 1n, targetTable: 'projects', amount: 2n * 10n**18n });
 *
 *   // Relation write (ERC-20 — approve wire first)
 *   await ${ast.table}.approveWire(wire, cUsdAddress, amount);
 *   await ${ast.table}.relatedCreate({ wire, id: 3n, data, targetId: 1n, targetTable: 'projects', amount, token: cUsdAddress });
 */
export class ${contractName}Model extends Model<${toPascal(ast.table)}Record> {
  constructor(
    tableAddress : string,
    signer       : ethers.Signer,
    keypair      : EncryptionKeypair,
    schema?      : SchemaDefinition,
  ) {
    super('${ast.table}', tableAddress, signer, keypair, {
      counterFields: [${counterFieldNamesLiteral}],
      schema,
    });
  }
}
`;
}

// ─────────────────────────────────────────────────────────────
//  Public API
// ─────────────────────────────────────────────────────────────

/**
 * Generate Solidity + ABI + TypeScript SDK bindings from a table AST.
 * Fully deterministic — same AST always produces same output.
 */
export function generateTable(ast: TableAst): CompilerOutput {
  const contractName = `${toPascal(ast.table)}Table`;
  const solidity     = generateSolidity(ast, contractName);
  const sdkBindings  = generateSdkBindings(ast, contractName);
  const abi          = buildAbi();
  const schemaBytes  = encodeSchemaBytes(ast);

  return { ast, contractName, solidity, sdkBindings, abi, schemaBytes };
}
