/**
 * @file   generator.ts
 * @notice TableAst → Solidity contract + TypeScript SDK bindings + ABI
 *
 * The generator is purely deterministic: same AST in, same output out.
 * No filesystem access, no randomness.
 */

import {
  Abi,
  AbiFunctionDef,
  AbiParam,
  CompilerOutput,
  SQL_TO_SOLIDITY,
  SQL_TO_TS,
  TableAst,
} from './types.js';
import { ethers } from 'ethers';

// ─────────────────────────────────────────────────────────────
//  Name helpers
// ─────────────────────────────────────────────────────────────

function toPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

// ─────────────────────────────────────────────────────────────
//  ABI builder helpers
// ─────────────────────────────────────────────────────────────

function fn(
  name: string,
  inputs: AbiParam[],
  outputs: AbiParam[],
  mutability: 'pure' | 'view' | 'nonpayable' | 'payable' = 'nonpayable'
): AbiFunctionDef {
  return { type: 'function', name, inputs, outputs, stateMutability: mutability };
}

function p(name: string, type: string, internalType?: string): AbiParam {
  return { name, type, internalType: internalType ?? type };
}

// ─────────────────────────────────────────────────────────────
//  Schema → on-chain schemaBytes (ABI-encoded for storage)
// ─────────────────────────────────────────────────────────────

function encodeSchemaBytes(ast: TableAst): string {
  const abiCoder = ethers.AbiCoder.defaultAbiCoder();
  const fieldNames  = ast.fields.map((f) => f.name);
  const fieldTypes  = ast.fields.map((f) => f.type);
  const fieldPrimary= ast.fields.map((f) => f.primary);
  const encoded = abiCoder.encode(
    ['string', 'string[]', 'string[]', 'bool[]'],
    [ast.table, fieldNames, fieldTypes, fieldPrimary]
  );
  return encoded;
}

// ─────────────────────────────────────────────────────────────
//  Solidity generator
// ─────────────────────────────────────────────────────────────

function generateSolidity(ast: TableAst, contractName: string): string {
  const fieldDocs = ast.fields
    .map((f) => `${f.name}:${f.type}${f.primary ? ' (PK)' : ''}`)
    .join(', ');

  const pkField   = ast.fields.find((f) => f.primary)!;
  const pkSolType = SQL_TO_SOLIDITY[pkField.type]; // always uint256

  return `\
// SPDX-License-Identifier: MIT
// Generated by @web3ql/compiler — DO NOT EDIT
// Table: ${ast.table}  Fields: ${fieldDocs}
pragma solidity ^0.8.20;

import "../contracts/Web3QLTable.sol";

/**
 * @title  ${contractName}
 * @notice Web3QL encrypted table for "${ast.table}".
 *         Schema: ${fieldDocs}
 *
 * Key derivation:
 *   bytes32 key = keccak256(abi.encodePacked("${ast.table}", id))
 *
 * All read/write operations delegate to Web3QLTable's encrypted storage.
 */
contract ${contractName} is Web3QLTable {

    // ----------------------------------------------------------
    //  Key derivation — deterministic, collision-resistant
    // ----------------------------------------------------------

    function _getKey(${pkSolType} id) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked("${ast.table}", id));
    }

    // ----------------------------------------------------------
    //  CRUD helpers (thin wrappers adding uint id → bytes32 key)
    // ----------------------------------------------------------

    function insert(
        ${pkSolType}  id,
        bytes calldata ciphertext,
        bytes calldata encryptedKey
    ) external {
        write(_getKey(id), ciphertext, encryptedKey);
    }

    function readRecord(
        ${pkSolType} id
    ) external view returns (
        bytes memory ciphertext,
        bool         deleted,
        uint256      version,
        uint256      updatedAt,
        address      owner_
    ) {
        return read(_getKey(id));
    }

    function updateRecord(
        ${pkSolType}  id,
        bytes calldata ciphertext,
        bytes calldata encryptedKey
    ) external {
        update(_getKey(id), ciphertext, encryptedKey);
    }

    function deleteRecordById(${pkSolType} id) external {
        deleteRecord(_getKey(id));
    }

    // ----------------------------------------------------------
    //  Access control helpers
    // ----------------------------------------------------------

    function grantRecordAccess(
        ${pkSolType}  id,
        address        user,
        Role           role,
        bytes calldata encryptedKeyForUser
    ) external {
        grantAccess(_getKey(id), user, role, encryptedKeyForUser);
    }

    function revokeRecordAccess(${pkSolType} id, address user) external {
        revokeAccess(_getKey(id), user);
    }

    function getEncryptedKey(${pkSolType} id) external view returns (bytes memory) {
        return getMyEncryptedKey(_getKey(id));
    }

    // ----------------------------------------------------------
    //  Views
    // ----------------------------------------------------------

    function recordExists(${pkSolType} id) external view returns (bool) {
        return recordExists(_getKey(id));
    }

    function recordOwner(${pkSolType} id) external view returns (address) {
        return _records[_getKey(id)].owner;
    }

    function getCollaboratorCount(${pkSolType} id) external view returns (uint8) {
        return collaboratorCount(_getKey(id));
    }
}
`;
}

// ─────────────────────────────────────────────────────────────
//  ABI builder
// ─────────────────────────────────────────────────────────────

const RECORD_TUPLE_OUTPUT: AbiParam = {
  name: '',
  type: 'tuple',
  internalType: 'struct Web3QLTable.RecordMeta',
  components: [
    p('ciphertext', 'bytes'),
    p('deleted',    'bool'),
    p('version',    'uint256'),
    p('updatedAt',  'uint256'),
    p('owner_',     'address'),
  ],
};

function buildAbi(): Abi {
  return [
    // CRUD
    fn('insert',           [p('id','uint256'), p('ciphertext','bytes'), p('encryptedKey','bytes')],     []),
    fn('readRecord',       [p('id','uint256')],
      [p('ciphertext','bytes'), p('deleted','bool'), p('version','uint256'), p('updatedAt','uint256'), p('owner_','address')],
      'view'
    ),
    fn('updateRecord',     [p('id','uint256'), p('ciphertext','bytes'), p('encryptedKey','bytes')],     []),
    fn('deleteRecordById', [p('id','uint256')],                                                         []),
    // Access control
    fn('grantRecordAccess',  [p('id','uint256'), p('user','address'), p('role','uint8'), p('encryptedKeyForUser','bytes')], []),
    fn('revokeRecordAccess', [p('id','uint256'), p('user','address')],                                  []),
    fn('getEncryptedKey',    [p('id','uint256')],  [p('','bytes')], 'view'),
    // Views
    fn('recordExists',       [p('id','uint256')],   [p('','bool')],    'view'),
    fn('recordOwner',        [p('id','uint256')],   [p('','address')], 'view'),
    fn('getCollaboratorCount', [p('id','uint256')], [p('','uint8')],   'view'),
    // Events from Web3QLTable
    {
      type: 'event', name: 'RecordWritten',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('owner','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'RecordUpdated',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('actor','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'RecordDeleted',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('owner','address'), indexed: true } as any,
        p('version','uint256'),
        p('updatedAt','uint256'),
      ],
    },
    {
      type: 'event', name: 'AccessGranted',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('user','address'), indexed: true } as any,
        p('role','uint8'),
      ],
    },
    {
      type: 'event', name: 'AccessRevoked',
      inputs: [
        { ...p('key','bytes32'), indexed: true } as any,
        { ...p('user','address'), indexed: true } as any,
      ],
    },
  ];
}

// ─────────────────────────────────────────────────────────────
//  TypeScript SDK bindings generator
// ─────────────────────────────────────────────────────────────

function generateSdkBindings(ast: TableAst, contractName: string): string {
  const pk     = ast.fields.find((f) => f.primary)!;
  const pkTs   = SQL_TO_TS[pk.type]; // bigint

  const fieldTypes = ast.fields
    .map((f) => `  ${f.name}: ${SQL_TO_TS[f.type]};`)
    .join('\n');

  return `\
/**
 * Auto-generated Web3QL SDK bindings for "${ast.table}".
 * DO NOT EDIT — regenerate via: web3ql compile
 *
 * Depends on @web3ql/sdk for end-to-end encrypted read/write.
 */
import { ethers }                                            from 'ethers';
import {
  EncryptedTableClient,
  PublicKeyRegistryClient,
  Role,
  type EncryptionKeypair,
  type RawRecord,
}                                                            from '@web3ql/sdk';

// ── Record shape ─────────────────────────────────────────────
export interface ${toPascal(ast.table)}Record {
${fieldTypes}
}

const TABLE_NAME = '${ast.table}';

// ── Typed client ─────────────────────────────────────────────
/**
 * ${contractName}Client — encrypted read/write for the "${ast.table}" table.
 *
 * @example
 *   const client = new ${contractName}Client(tableAddress, signer, keypair);
 *
 *   // Write (auto-encrypts)
 *   await client.insert(1n, JSON.stringify({ id: 1, name: 'Alice' }));
 *
 *   // Read (auto-decrypts)
 *   const data = await client.read(1n);
 *   const row  = JSON.parse(data) as ${toPascal(ast.table)}Record;
 *
 *   // Share with Bob (Bob must be registered in the PublicKeyRegistry)
 *   await client.share(1n, bobAddress, Role.VIEWER, registry);
 */
export class ${contractName}Client extends EncryptedTableClient {

  constructor(
    tableAddress : string,
    signer       : ethers.Signer,
    keypair      : EncryptionKeypair,
  ) {
    super(tableAddress, signer, keypair);
  }

  // ── Key derivation ──────────────────────────────────────────

  /** Derive the on-chain bytes32 key for a record id. */
  key(id: ${pkTs}): string {
    return this.deriveKey(TABLE_NAME, id);
  }

  // ── CRUD ────────────────────────────────────────────────────

  /**
   * Insert a new encrypted record.
   * @param id      Primary key value.
   * @param payload Serialised row — e.g. JSON.stringify(row).
   */
  async insert(id: ${pkTs}, payload: string): Promise<ethers.TransactionReceipt> {
    return this.writeRaw(this.key(id), payload);
  }

  /**
   * Read and decrypt a record.
   * Returns the raw string you passed to insert() / update().
   */
  async read(id: ${pkTs}): Promise<string> {
    return this.readPlaintext(this.key(id));
  }

  /**
   * Read as raw bytes (if you stored binary data).
   */
  async readBytes(id: ${pkTs}): Promise<Uint8Array> {
    return super.readBytes(this.key(id));
  }

  /**
   * Get the raw on-chain record (still encrypted).
   */
  async readRaw(id: ${pkTs}): Promise<RawRecord> {
    return super.readRaw(this.key(id));
  }

  /**
   * Update an existing record.
   * Rotates the symmetric key — call reshare() afterwards if needed.
   */
  async update(id: ${pkTs}, payload: string): Promise<ethers.TransactionReceipt> {
    return this.updateRaw(this.key(id), payload);
  }

  /** Delete a record and scrub all collaborator key copies. */
  async del(id: ${pkTs}): Promise<ethers.TransactionReceipt> {
    return this.deleteRecord(this.key(id));
  }

  // ── Sharing ─────────────────────────────────────────────────

  /**
   * Share a record with another address.
   * They must have registered their public key in the PublicKeyRegistry.
   */
  async share(
    id        : ${pkTs},
    recipient : string,
    role      : Role,
    registry  : PublicKeyRegistryClient,
  ): Promise<ethers.TransactionReceipt> {
    return super.share(this.key(id), recipient, role, registry);
  }

  /** Revoke a user's access to a record. */
  async revoke(id: ${pkTs}, user: string): Promise<ethers.TransactionReceipt> {
    return super.revoke(this.key(id), user);
  }

  // ── Views ────────────────────────────────────────────────────

  async exists(id: ${pkTs}): Promise<boolean> {
    return super.exists(this.key(id));
  }

  async owner(id: ${pkTs}): Promise<string> {
    return super.owner(this.key(id));
  }

  async collaboratorCount(id: ${pkTs}): Promise<number> {
    return super.collaboratorCount(this.key(id));
  }
}
`;
}

// ─────────────────────────────────────────────────────────────
//  Public API
// ─────────────────────────────────────────────────────────────

/**
 * Generate Solidity + ABI + TypeScript SDK bindings from a table AST.
 * Fully deterministic — same AST always produces same output.
 */
export function generateTable(ast: TableAst): CompilerOutput {
  const contractName = `${toPascal(ast.table)}Table`;
  const solidity     = generateSolidity(ast, contractName);
  const sdkBindings  = generateSdkBindings(ast, contractName);
  const abi          = buildAbi();
  const schemaBytes  = encodeSchemaBytes(ast);

  return { ast, contractName, solidity, sdkBindings, abi, schemaBytes };
}
